#the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo pre-build phase
  build:
    commands:
      - echo build phase
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo artifacts copied in s3
# Include only the files required for your application to run.
artifacts:
  files:
    - app.js
    - package.json
    - /**/*
